### ISSUE TITLE
Douban cannot locate login successfully

### ISSUE THREAD

**Issue by lorenzoromani1983** [Greenwolf/social_mapper#108]
Hi.
I am having troubles when using SM on Douban.
I get this error:

[+] Douban Login Page loaded successfully [+]
Traceback (most recent call last):
  File "/home/osint/social_mapper/social_mapper.py", line 1143, in <module>
    peoplelist = fill_douban(peoplelist)
  File "/home/osint/social_mapper/social_mapper.py", line 707, in fill_douban
    DoubanfinderObject.doLogin(douban_username,douban_password)
  File "/home/osint/social_mapper/modules/doubanfinder.py", line 33, in doLogin
    wbUsername = self.driver.find_element_by_id("email")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="email"]

maybe something changed in the login page. Is it possible to fix it?
thank you :)

**Comment by lorenzoromani1983** [comment]
Easy to fix: just change the login url to douban.com and not douban.com/login in social_mapper.py

**Comment by Greenwolf** [comment]
Brilliant, thanks for updating us with a fix! Much appreciated!

**Comment by Greenwolf** [comment]
Just to confirm, you meant change it in 'doubanfinder.py' right?

**Comment by lorenzoromani1983** [comment]
exactly :)
