### ISSUE TITLE
EasyProcessCheckInstalledError

### ISSUE THREAD

**Issue by lorenzoromani1983** [Greenwolf/social_mapper#119]
Hi. I believe I carefully followed all instructions (Kali Linux):
- Installed Firefox Quantum and added to PATH
- Uninstalled Firefox-ESR
- Downloaded Geckodriver and added to PATH
- Installed all the package (I had to separately install Cmake with pip install cmake).
Now I get this (company search mode):

Traceback (most recent call last):
  File "social_mapper.py", line 1121, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 218, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/social_mapper/modules/twitterfinder.py", line 15, in __init__
    display = Display(visible=0, size=(1600, 1024))
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 53, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 40, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 182, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!

**Comment by lorenzoromani1983** [comment]
looks like I managed to fix it by installing xvfb on kali (apt-get install xvfb).
