### ISSUE TITLE
Error Filling out Facebook Profiles [-] Message: connection refused

### ISSUE THREAD

**Issue by Kuro-Arigami** [Greenwolf/social_mapper#157]
-] Error Filling out Facebook Profiles [-]
Message: connection refused

[-]
Traceback (most recent call last):
  File "social_mapper.py", line 1138, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 303, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/home/kuro/Desktop/social_mapper/modules/twitterfinder.py", line 24, in __init__
    self.driver = webdriver.Firefox(firefox_profile=firefoxprofile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: connection refused

**Comment by Greenwolf** [comment]
I think this is a network issue, Facebook is working for me.
