### ISSUE TITLE
twitter

### ISSUE THREAD

**Issue by velbert7** [Greenwolf/social_mapper#160]
root@E4-42-A6-8D-12-6F:/home/velbert7/social_mapper# python3 social_mapper.py -f imagefolder -i /home/velbert7/social_mapper/Input-Examples/imagefolder -m fast -tw
Traceback (most recent call last):
  File "social_mapper.py", line 1138, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "social_mapper.py", line 303, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/home/velbert7/social_mapper/modules/twitterfinder.py", line 24, in __init__
    self.driver = webdriver.Firefox(firefox_profile=firefoxprofile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 174, in __init__
    keep_alive=True)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

**Comment by Greenwolf** [comment]
Looks like a selenium installation issue, try installing on Kali Linux or OSX with the most recent version, twitter is verified as working.
