### ISSUE TITLE
error

### ISSUE THREAD

**Issue by iamirror** [Greenwolf/social_mapper#173]
File "/usr/local/lib/python3.8/dist-packages/easyprocess/__init__.py", line 168, in start
    self.popen = subprocess.Popen(
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Xvfb'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "social_mapper.py", line 1148, in <module>
    peoplelist = fill_instagram(peoplelist)
  File "social_mapper.py", line 381, in fill_instagram
    InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
  File "/root/social_mapper/modules/instagramfinder.py", line 16, in __init__
    display = Display(visible=0, size=(1600, 1024))
  File "/usr/local/lib/python3.8/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python3.8/dist-packages/pyvirtualdisplay/display.py", line 53, in display_class
    cls.check_installed()
  File "/usr/local/lib/python3.8/dist-packages/pyvirtualdisplay/xvfb.py", line 40, in check_installed
    p.call()
  File "/usr/local/lib/python3.8/dist-packages/easyprocess/__init__.py", line 141, in call
    self.start().wait(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/easyprocess/__init__.py", line 174, in start
    raise EasyProcessError(self, "start error")
easyprocess.EasyProcessError: start error <EasyProcess cmd_param=['Xvfb', '-help

**Comment by Greenwolf** [comment]
What OS is this? Try using Kali or OSX with XQuartz terminal.
