### ISSUE TITLE
shutil.copytree

### ISSUE THREAD

**Issue by RWayne93** [Greenwolf/social_mapper#197]
hello. ran into an issue on running social_mapper managed to get everything working on mac but now im runnign into this issue. here is the traceback 

[+] Instagram Login Page loaded successfully [+]
[+] Instagram Login Success [+]

Instagram Check 1/1 : no smile                                

Results file: SM-Results/results-social-mapper.csv
HTML file: SM-Results/results-social-mapper.html

Traceback (most recent call last):
  File "social_mapper.py", line 1692, in <module>
    shutil.copytree(args.input, outputfoldername)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 455, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/usr/local/bin/../../../Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: 'SM-Results/-Users-user-Desktop-OpenCV_Projects-search--social-mapper'

if anybody knows how to solve this that would be great.

**Comment by Greenwolf** [comment]
Haha, i wrote this piece of code thinking like... no one will be running the same imagefolder scan more than once! 

More than one person has mentioned error to me now, so i will fix it 😆

**Comment by Greenwolf** [comment]
Should be fixed!
