### ISSUE TITLE
Guys pls help do all with instruction and this .

### ISSUE THREAD

**Issue by ANANIMLG** [Greenwolf/social_mapper#217]
python social_mapper.py -f imagefolder -i /home/danil/Desktop/soft/social_mapper/Input-Examples/imagefolder/ -m fast -ig
Traceback (most recent call last):
  File "/home/danil/Desktop/soft/social_mapper/social_mapper.py", line 1266, in <module>
    peoplelist = fill_instagram(peoplelist)
  File "/home/danil/Desktop/soft/social_mapper/social_mapper.py", line 410, in fill_instagram
    InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
  File "/home/danil/Desktop/soft/social_mapper/modules/instagramfinder.py", line 30, in __init__
    self.driver = webdriver.Firefox(firefox_profile=firefoxprofile, options=opts)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by ANANIMLG** [comment]
Do all . Remove and install firefox new-last version . Update package and removing . 
OC :  ParrotSecurity
Write my instagram in nano social_mapper.py (im do this )
Run with python , python 2

**Comment by ANANIMLG** [comment]
Me seems problem in FireFox and him webdriver i dk what doing
 Help

**Comment by littlewish89** [comment]
> python social_mapper.py -f imagefolder -i /home/danil/Desktop/soft/social_mapper/Input-Examples/imagefolder/ -m fast -ig
> 
> Traceback (most recent call last):
> 
>   File "/home/danil/Desktop/soft/social_mapper/social_mapper.py", line 1266, in <module>
> 
>     peoplelist = fill_instagram(peoplelist)
> 
>   File "/home/danil/Desktop/soft/social_mapper/social_mapper.py", line 410, in fill_instagram
> 
>     InstagramfinderObject = instagramfinder.Instagramfinder(showbrowser)
> 
>   File "/home/danil/Desktop/soft/social_mapper/modules/instagramfinder.py", line 30, in __init__
> 
>     self.driver = webdriver.Firefox(firefox_profile=firefoxprofile, options=opts)
> 
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
> 
>     RemoteWebDriver.__init__(
> 
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
> 
>     self.start_session(capabilities, browser_profile)
> 
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
> 
>     response = self.execute(Command.NEW_SESSION, parameters)
> 
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
> 
>     self.error_handler.check_response(response)
> 
>   File "/usr/lib/python3/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> 
>     raise exception_class(message, screen, stacktrace)
> 
> selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

- @

**Comment by ANANIMLG** [comment]
thx
