### ISSUE TITLE
http.cookiejar

### ISSUE THREAD

**Issue by anujsahad07** [Greenwolf/social_mapper#220]
sir, when i will apply this command then show this error what i will do ?
please solve this issue

python social_mapper.py -h

Traceback (most recent call last):
  File "social_mapper.py", line 5, in <module>
    import http.cookiejar
ImportError: No module named http.cookiejar

**Comment by littlewish89** [comment]
Who am I

**Comment by Redoxahmii** [comment]
> sir, when i will apply this command then show this error what i will do ?
> please solve this issue
> 
> python social_mapper.py -h
> 
> Traceback (most recent call last):
> File "social_mapper.py", line 5, in
> import http.cookiejar
> ImportError: No module named http.cookiejar

Use python3 instead of python
