### ISSUE TITLE
Not Working at all

### ISSUE THREAD

**Issue by BassemFarrag** [Greenwolf/social_mapper#241]
Hi,
When I try this Command after install everything, does not working
The Command:
`python3 social_mapper.py -f imagefolder -i /root/social_mapper/Input-Examples/imagefolder/ -m fast -fb -tw -ig`

The error message :
`[-] Error Filling out Facebook Profiles [-]
Message: Failed to read marionette port

[-]
Traceback (most recent call last):
  File "/root/social_mapper/social_mapper.py", line 1256, in <module>
    peoplelist = fill_twitter(peoplelist)
  File "/root/social_mapper/social_mapper.py", line 326, in fill_twitter
    TwitterfinderObject = twitterfinder.Twitterfinder(showbrowser)
  File "/root/social_mapper/modules/twitterfinder.py", line 32, in __init__
    self.driver = webdriver.Firefox(firefox_profile=firefoxprofile, options=opts)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 177, in __init__
    super().__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 276, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 369, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 434, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: Failed to read marionette port
`
![Screenshot from 2022-08-15 18-36-08](https://user-images.githubusercontent.com/63361520/184677760-f8686e1b-a419-4d9d-8a1d-cdd5d2a08876.png)

I wish to find someone help me to fix that.

**Comment by thaoph901** [comment]
add selenium new version
